### ISSUE TITLE
Clarify documentation on allowed_cidr_list

### ISSUE THREAD

**Issue by siddharthist** [hashicorp/vault-ssh-helper#16]
Right now, the documentation states:
> List of comma-separated CIDR blocks. If the IP used by the user to connect to the host is different than the address(es) of the host's network interface(s) (for instance, if the address is NAT-ed), then vault-ssh-helper cannot authenticate the IP. In these cases, the IP returned by Vault will be matched with the CIDR blocks in this list. If it matches, the authentication succeeds. (Use with caution)

First, 
> If the IP used by the user to connect to the host is different than the address(es) of the host's network interface(s) 

is somewhat unclear. What is "the host"? Is this saying "if the IP used by the user isn't on the host being connected to"? Why can't ssh-helper authenticate the IP?

Second, what is an "IP returned by Vault"? 

Third, is the password checked in this case? The README says "authentication succeeds", does this mean "authentication succeeds if Vault correctly authenticates the password as well"?

**Comment by vishalnayak** [comment]
@siddharthist 
>What is "the host"? Is this saying "if the IP used by the user isn't on the host being connected to"? Why can't ssh-helper authenticate the IP?

Host is the remote machine to which client/user is trying to login.
And yes, it is saying "IP used by the user isn't on the host being connected to".

Vault API for creating OTP takes in a IP address and a username.
`vault write /ssh/creds/<role name> ip=x.x.x.x username=yyy`
The generated OTP in Vault is always associated with an IP address and a username.

During connection establishment, vault-ssh-helper reads the OTP entered by the user and sends it to Vault for verification. If Vault finds an entry for this OTP, it will respond with the associated IP and the username. For the authentication to succeed, the IP address returned by Vault should match the IP address of the remote machine (where vault-ssh-helper is running) and the username should match as well.

Now, it may so happen that the resolved IP during creation of OTP may not be the the address of the network interface in the remote host (many remote hosts may be lying under an umbrella NAT-ed address). In such cases, vault-ssh-helper will have no way of authenticating the connection. The `allowed_cidr_list` should mention the outside facing IP address of the remote hosts. This way vault-ssh-helper will check the IP returned by Vault in this list.

Note that Vault is not authenticating the SSH connection. It only verifies if the OTP is a valid one and responds with the associated IP and username, that's it.

Hope this helps!

**Comment by siddharthist** [comment]
@vishalnayak That's exactly what I was looking for! Thank you! And I think I got my setup all working now thanks to your help :) [mantl.io](https://github.com/CiscoCloud/mantl) will soon have OTPs!

**Comment by vishalnayak** [comment]
@siddharthist That's great news!

**Comment by jefferai** [comment]
@siddharthist That is super neato. It's great that you guys are bringing Vault in as a first-class citizen.
