### ISSUE TITLE
make vault_addr a list

### ISSUE THREAD

**Issue by jaychris** [hashicorp/vault-ssh-helper#19]
It would be convenient to have vault_addr be a list so that you can specify a backup Vault server in the case that the primary one is unavailable (for whatever reason).  

I don't know GoLang or I would take a crack at it... :-)

**Comment by vishalnayak** [comment]
@jaychris `vault-ssh-helper` is a client. It need not know all the addresses of Vault servers.
If Vault is running in HA mode, when and if the active Vault node goes down, the standby node would take over and the requests should just work.

**Comment by jaychris** [comment]
Right, but that's actually not the case - the client config is set in config.hcl (in /etc/vault-ssh-helper.d) in my case and that seems the be the limit of what the client will handle - if you try to do an auth against a client, where the vault_addr specified in client.hcl is down, then you get an error response from PAM:

Mar 14 16:32:05 docker sshd[1847]: error: PAM: System error for ubuntu from 192.168.98.10

... because the client that pam is configured to use (vault-ssh-helper) doesn't appear to know how to reach the other vaults and the vault it DOES know about, isn't available to tell it how to reach the leader... :-/

See what I am saying?  I can provide more detail if you need it.  But, it pretty clearly does not work if the Vault it is configured to talk to is not available...

**Comment by jaychris** [comment]
I'm happy to provide debug output (I can repro this at will) if there is a debug switch for the client...

**Comment by jefferai** [comment]
Hi @jaychris ,

You can pass a hostname as the `vault_addr` parameter, so you should get the behavior you want by using `vault.prod.company.com` as the `vault_addr` host.

**Comment by jaychris** [comment]
Here is the current config.hcl:

```
vault_addr = "https://vault.sea.company.com"
allowed_cidr_list = "10.0.0.0/16,192.168.0.0/16"
ssh_mount_point = "ssh"
tls_skip_verify = false
```

And you are right, if I add "https://vault.prod.company.com", it works, because "vault.prod.company.com" works.  But, that's totally arbitrary right?  What if I have "vault_addr" set to be "vault.prod.company.com" and THAT vault goes down?  The exact same problem that I have now - vault-ssh-helper will fail to authenticate because it does not find an available Vault, *regardless* of whether I am operating in HA mode or not.  To fix, I either have to bring the local vault back online OR manually update "config.hcl" with the address of a Vault is working.  All I am saying here, is to change that setting to a list so that I can specify another Vault to check if the local Vault is lost, because vault-ssh-helper doesn't do it on it's own.

If the "vault_addr" that the vault-ssh-helper points at is unavailable (not just *sealed*, but completed unavailable - down, crashed, whatever) then the ssh-helper will fail to authenticate.

Seriously, just try it - setup a small HA Vault network, point vault-ssh-helper at one (any) of the Vaults, then shut that Vault down (stop it, don't just seal it).  The outcome will be vault-ssh-helper will fail to work for logins.

**Comment by jaychris** [comment]
For the record, the same issue occurs if the local Vault is just sealed as well...

**Comment by jefferai** [comment]
@jaychris that 503 isn't coming from Vault, it's coming from your load balancer, and is likely happening because your load balancer is introducing delay between when your current active node goes down and when the new active node is discovered (we often see this on ELB due to its minimum 10-second health delay for marking a node down). When your load balancer discovers the new active instance, it should then work properly. Is that not the behavior you see?

**Comment by jaychris** [comment]
I'm not actually using a load balancer - I'm using HAproxy to terminate SSL locally for each instance.  I'm still a bit confused though on how the helper will be able to discover the other vault instances in the HA network when it only knows about the single vault instance that doesn't even have a process running...  the way we have this deployed is a single vault in various remote locations around the country, using Consul for the storage backend and single local HAProxy instance (running on the same server) to terminate SSL.  All of the Vaults are correctly showing both their local status (standby or active) and the leader.

If that is not a a recommended/supported setup, let me know, but it seemed simpler to implement that way.  If that is somehow breaking the HA portability, let me know.

**Comment by jefferai** [comment]
Hi @jaychris ,

Your setup is not one I've seen before, and does have some disadvantages -- one of them being the problem you're running into now. An important part of HA is knowing how to reach the current active node. The most common approaches are to either use a load balancer or service discovery. Either of those two approaches make this a non-issue, since you always query the same address and get back the active node. You don't specify how you're doing this in any other scenario (when using the Vault CLI or something like `curl`, for instance)...how are you connecting to the active node with other tools?

Also, why not simply terminate TLS within Vault itself? Using HAproxy just to terminate TLS also causes transitive trust issues.

**Comment by jaychris** [comment]
well, terminating SSL with HAproxy is (seemed) a lot simpler than dealing with application level TLS, which has historically been a PITA.  I can't conveniently count how many TLS SSL handshake errors I've had to track down over time.  I'm not sure why using HAproxy to terminate SSL would cause transitive trust issues - if I have a trusted cert for each domain that hosts a Vault, that seems pretty legit.

I'm not seeing the documentation on Vault where you setup service discovery (using Consul?  Seems like a cool solution).  A LB seems like an easy solution too.

It seems like what I am doing is not entirely recommended/intended so I'll change directions for one of the solutions above.  If there is something on doing service discovery for Vault with Consul, I'd definitely be interested.

Thanks for the help.  :-)

**Comment by jefferai** [comment]
Hi @jaychris ,

Go's TLS handling is pretty rock solid, unless you need to configure very specific parameters/behavior (which is possible in Go, but not mostly pulled out in Vault). The problem with using a load balancer/reverse proxy terminating TLS is the connection going from there to Vault. In some cases people use straight HTTP, which is a bad idea for pretty obvious reasons. It's better if that connection is also TLS, but it means that along the way the data exists in plaintext before reencrypting it.  A lot of people feel totally fine with that, but it's disallowed by PCI 3 and some other standards.

There isn't documentation in Vault about setting up service discovery as that's a very different problem with very different tools. However, Consul's documentation is extensive, if you want to use it. At a very simple level, you'd register Vault as a service in Consul along with a health check. Then your clients would simply query Consul, either via DNS or the HTTP API, to get the current active node. Vault's health endpoint uses HTTP status codes expected by Consul's health check mechanism. Keeping the health check timer low will decrease the time needed to roll over to a new active node, from a client perspective.

At some point, maybe 0.6, we'll probably add a health check from within Vault directly into Consul; this would allow Vault to manage the state of its nodes much more rapidly in some (although not all) situations.

**Comment by jaychris** [comment]
Ok, this is my last go round on this then I'll stop bugging you - assuming I implement your scenario where a load balance sits in front of my Vault servers (can't use ELB though because I have some non-EC2 Vaults).  I've fixed the backend TLS as you described.  The load balancer is working great, directly requests to the active Vault.

What happens now if one of my remote stations loses connectivity to *just*
