### ISSUE TITLE
GitHub/Bintray releases?

### ISSUE THREAD

**Issue by steve-jansen** [hashicorp/vault-ssh-helper#2]
Hi @vishalnayak 

Noticed that this repo doesn't have any tags yet, or GH releases.  It feels a bit awkward to clone and build the master branch for production use.

Do you have any plans to tag or ship binaries?

Warm regards,
Steve

**Comment by cbednarski** [comment]
@steve-jansen Thanks for the heads up. We should roll this under [releases.hashicorp.com](https://releases.hashicorp.com).

**Comment by sethvargo** [comment]
Done! https://releases.hashicorp.com/vault-ssh-helper/ :smile:

**Comment by steve-jansen** [comment]
Wow, thank you!

**Comment by BSick7** [comment]
That was fast! Thanks @sethvargo
