### ISSUE TITLE
FreeBSD binaries don't appear usable

### ISSUE THREAD

**Issue by inferiorhumanorgans** [hashicorp/vault-ssh-helper#22]
FreeBSD has used OpenPAM for a few versions now.  From the looks of it, there's no method of passing anything via stdio. There are definitely no log or expose_authotok options.  Likely the path of least resistance would be to build this as a shared library.

https://github.com/freebsd/freebsd/blob/stable/10/lib/libpam/modules/pam_exec/pam_exec.c

```
	/*
	 * XXX For additional credit, divert child's stdin/stdout/stderr
	 * to the conversation function.
	 */
```

**Comment by inferiorhumanorgans** [comment]
Note that this incompatibility will be true for all of the BSDs (and OSX) as they all use OpenPAM to the best of my knowledge.  A quick look at the Solaris docs on Oracle seems to indicate that a pam_exec module doesn't exist there at all.

**Comment by jefferai** [comment]
Ah, that's too bad. I'll remove the other BSDs from builds. (I think the build file was simply copied over at some point, rather than explicitly thinking it worked for BSDs.)

**Comment by macdice** [comment]
FYI FreeBSD 12 pam_exec.so now supports expose_authtok and it might be MFC'd to 11.x.
