### ISSUE TITLE
ssh connection not getting close after max-lease-duration 

### ISSUE THREAD

**Issue by shubhamitc** [hashicorp/vault-ssh-helper#29]
Hi, 
I have tuned my vault for max-lease-ttl to be 10h however the connection is still established even after 10h. This is not working as expected 
`# tmux ls `
`singh2: 1 windows (created Sun Apr 23 13:26:21 2017) [178x42]`
`[shubham@automation2 ~]$ date`
`Mon Apr 24 08:42:40 UTC 2017 `

Vault is mount point ssh is tuned with following command, 

`vault mount-tune -default-lease-ttl=10h -max-lease-ttl=10h ssh`

Vault version : 

`[shubham@xxxx ~]$ vault   version`
`Vault v0.7.0 ('614deacfca3f3b7162bbf30a36d6fc7362cd47f0')`

`vault status`
`Sealed: false`
`Key Shares: 5`
`Key Threshold: 3`
`Unseal Progress: 0`
`Unseal Nonce:`
`Version: 0.7.0`
`Cluster Name: vault-cluster-925f7c5f`
`Cluster ID: 194c7fb6-fde4-3ae3-a9b5-8048b9e16979`

`High-Availability Enabled: true`
	`Mode: active`
	`Leader: https://x.x.x.x:8200`

Thanks,

**Comment by jefferai** [comment]
Vault does not (and cannot) manage your session lifetime. Once the connection is established it's up to SSH to kill a connection if the credential used is no longer valid.
