### ISSUE TITLE
CentOS PAM

### ISSUE THREAD

**Issue by cornfeedhobo** [hashicorp/vault-ssh-helper#31]
The documentation for PAM integration seems to be targeted at Ubuntu users (although it does not specify).

It would be amazing if this was also covered for CentOS too

**Comment by nyetsche** [comment]
The CentOS configuration is the same as what's in the Readme. But for reference:

`/etc/pam.d/sshd`

```
#%PAM-1.0
auth        required    pam_sepermit.so
#auth       substack    password-auth # COMMENT OUT FOR SSH-HELPER
auth        include     postlogin
auth        requisite   pam_exec.so quiet expose_authtok log=/var/log/vaultssh.log /usr/local/bin/vault-ssh-helper -config=/etc/vault/vault_ssh.conf
auth        optional    pam_unix.so not_set_pass use_first_pass nodelay
# Used with polkit to reauthorize users in remote sessions
-auth       optional    pam_reauthorize.so prepare
account     required    pam_nologin.so
account     include     password-auth
#password   include     password-auth # COMMENT OUT FOR SSH-HELPER
# pam_selinux.so close should be the first session rule
session     required    pam_selinux.so close
session     required    pam_loginuid.so
# pam_selinux.so open should only be followed by sessions to be executed in the user context
session     required    pam_selinux.so open env_params
session     required    pam_namespace.so
session     optional    pam_keyinit.so force revoke
session     include     password-auth
session     include     postlogin
# Used with polkit to reauthorize users in remote sessions
-session   optional     pam_reauthorize.so prepare
```

`/etc/ssh/sshd_config` (abridged)

```
ChallengeResponseAuthentication yes
PasswordAuthentication no 
UsePAM yes  
```

**Comment by cornfeedhobo** [comment]
@nyetsche Yeah, I tested this to no avail. I will have free time to create another testing box this weekend and report back. Thanks.

**Comment by jagadish85** [comment]
Is Anyone able to configure correctly with SE linux enabled?

**Comment by mhmdio** [comment]
@jagadish85 Yes, Please do the following:
```bash
sudo su
setenforce 0
# Logout and Login using vault OTP 
grep sshd_t /var/log/audit/audit.log | audit2allow -m vault-helper > vault-helper.te
make -f /usr/share/selinux/devel/Makefile vault-helper.pp
semodule -i vault-helper.pp
semodule -l | grep vault
setenforce 1
# Logout and Login using vault OTP 
```

**Comment by heretogo** [comment]
I am getting the following output when I try and auth to my Centos 6.9 host running vault-ssh-helper

`Mar 20 12:30:07 vaulthost sshd[6900]: Received disconnect from 10.1.1.1: 11: disconnected by user
Mar 20 12:30:07 vaulthost sshd[6898]: pam_unix(sshd:session): session closed for user vault_ssh_user
Mar 20 12:30:09 vaulthost sshd[8249]: PAM (sshd) illegal module type: @include
Mar 20 12:30:09 vaulthost sshd[8249]: PAM pam_parse: expecting return value; [...common-account]
Mar 20 12:30:09 vaulthost sshd[8249]: PAM (sshd) no module name supplied
Mar 20 12:30:09 vaulthost sshd[8249]: PAM (sshd) illegal module type: @include
Mar 20 12:30:09 vaulthost sshd[8249]: PAM pam_parse: expecting return value; [...common-session]
Mar 20 12:30:09 vaulthost sshd[8249]: PAM (sshd) no module name supplied
Mar 20 12:30:09 vaulthost sshd[8249]: PAM (sshd) illegal module type: @include
Mar 20 12:30:09 vaulthost sshd[8249]: PAM pam_parse: expecting return value; [...common-password]
Mar 20 12:30:09 vaulthost sshd[8249]: PAM (sshd) no module name supplied
Mar 20 12:30:09 vaulthost sshd[8251]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=vaultclient.host.com  user=vault_ssh_user`

**Comment by nyetsche** [comment]
It sounds like your config file has a typo or misconfiguration somewhere. I don't think it's directly related to this repo. https://stackoverflow.com/questions/43608930/illegal-module-type-etc-login-defs

**Comment by heretogo** [comment]
Fixed /etc/pam.d/sshd config based on nyetsche's example (some small differences in our original files).

**Comment by gigascake** [comment]
After Upper settings, and then vault ssh login
$ vault ssh -mode otp -role otp_key_role user@XXX.XXX.XXX.XXX
Permission denied, please try again.
failed to run ssh command: exit status 5

Solution is public-key. Is this normal Action? 

I think that problems. what's wrong?

**Comment by wrj2wmy** [comment]
Eventually find out that the real command which makes it work:
`**setenforce 0**`

It will change the SELinux mode from "enforcing" to "permissive".
`sestatus | grep -i mode` will tell the truth

**Comment by alpozcan** [comment]
I put together an SELinux module to allow Vault OTP to function. It allows vault-ssh-helper to open/write to log files and communicate to the Vault server on port 443

https://gist.github.com/alpozcan/cbe15d2b085f56090dff6da7a2b73587

Tested to work on Amazon Linux 2.

**Comment by devcharted** [comment]
`setsebool -P nis_enabled=1` is sufficient

**Comment by WannaBeGeekster** [comment]
> ```shell
> setenforce 1
> ```

yum -y install policycoreutils-python-utils
yum -y groupinstall "Development Tools"
yum -y install selinux-policy-devel


These three commands should be ran first on a base install of CentOS 8.  Thank you for this walkthrough it was extremely helpful!

**Comment by swenson** [comment]
I think this is resolved, or at least not as relevant now? I'll close this for now.
