### ISSUE TITLE
updatedeps not working...

### ISSUE THREAD

**Issue by flynn1973** [hashicorp/vault-ssh-helper#34]
any hints?

root@aixbuildhost: /usr/local/go/src/github.com/hashicorp/vault-ssh-helper # gmake updatedeps
go get -u github.com/mitchellh/gox
echo $(go list ./... | grep -v /vendor/) \
        | xargs go list -f '{{ join .Deps "\n" }}{{ printf "\n" }}{{ join .TestImports "\n" }}' \
        | grep -v github.com/hashicorp/vault-ssh-helper \
        | xargs go get -f -u -v
go install: no install location for directory  outside GOPATH
        For more details see: 'go help gopath'
go install: no install location for directory  outside GOPATH
        For more details see: 'go help gopath'
go install: no install location for directory  outside GOPATH
        For more details see: 'go help gopath'
go install: no install location for directory  outside GOPATH
        For more details see: 'go help gopath'
Makefile:58: recipe for target 'updatedeps' failed
gmake: *** [updatedeps] Error 1
root@aixbuildhost: /usr/local/go/src/github.com/hashicorp/vault-ssh-helper # go env
GOARCH="ppc"
GOBIN=""
GOEXE=""
GOHOSTARCH="ppc"
GOHOSTOS="aix"
GOOS="aix"
GOPATH="/usr/local/go"
GORACE=""
GOROOT="/opt/freeware"
GOTOOLDIR="/opt/freeware/libexec/gcc/powerpc-ibm-aix7.1.0.0/7.1.0"
GCCGO="/opt/freeware/bin/gccgo"
CC="/opt/freeware/bin/gcc"
GOGCCFLAGS="-fPIC -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build570047875=/tmp/go-build -gno-record-gcc-switches"
CXX="/opt/freeware/bin/g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"

**Comment by flynn1973** [comment]
could anyone help me out of this disaster? i urgently need this binary for aix!

root@aixbuildhost: /root/go/src/github.com/hashicorp/vault-ssh-helper # gmake
go generate
==> Removing old directory...
==> Building...
2018/03/26 15:26:40 Unable to parse current go version: 1.8.1 gccgo (GCC) 7.1.0
Malformed version: 1.8.1 gccgo (GCC) 7.1.0
No valid platforms to build for. If you specified a value
for the 'os', 'arch', or 'osarch' flags, make sure you're
using a valid value.
Makefile:14: recipe for target 'dev' failed
gmake: *** [dev] Error 1

**Comment by jefferai** [comment]
Try building with just `go build`. However, AIX is generally not supported by Go so I'm not sure it's even possible to build for AIX at all.

**Comment by flynn1973** [comment]
what should i say...thank you very much!

root@aixbuildhost: /root/go/src/github.com/hashicorp/vault-ssh-helper # ./vault-ssh-helper -h
Usage: vault-ssh-helper [options]

  vault-ssh-helper takes the One-Time-Password (OTP) from the client and
  validates it with Vault server. This binary should be used as an external
  command for authenticating clients during for keyboard-interactive auth
  of SSH server.

Options:

  -config=<path>              The path on disk to a configuration file.
  -dev                        Run the helper in "dev" mode, (such as testing or http)
  -verify-only                Verify the installation and communication with Vault server
  -version                    Display version.
root@aixbuildhost: /root/go/src/github.com/hashicorp/vault-ssh-helper # ldd vault-ssh-helper
vault-ssh-helper needs:
         /usr/lib/libc.a(shr.o)
         /opt/freeware/lib/libgo.a(libgo.so.11)
         /opt/freeware/lib/libgcc_s.a(shr.o)
         /usr/lib/librtl.a(shr.o)
         /unix
         /usr/lib/libcrypt.a(shr.o)
         /usr/lib/libpthread.a(shr_xpg5.o)
         /usr/lib/libpthread.a(shr_comm.o)
         /usr/lib/libpthreads.a(shr_comm.o)

**Comment by jefferai** [comment]
Glad it's working!
