### ISSUE TITLE
pam_unix.so configuration error

### ISSUE THREAD

**Issue by Saloshp** [hashicorp/vault-ssh-helper#35]
The [documentation](https://github.com/hashicorp/vault-ssh-helper#pam-configuration) specifies the following line
`auth optional pam_unix.so not_set_pass use_first_pass nodelay`

However, pam_unix.so does not support the `not_set_pass` option, 
journal snippet:
> ...
> Sep 11 22:30:01 ha01 sshd[21821]: pam_unix(sshd:auth): unrecognized option [not_set_pass]
> ...
---

```bash
[root@ha01 ~]# uname -a
Linux ha01 4.18.6-arch1-1-ARCH #1 SMP PREEMPT Wed Sep 5 11:54:09 UTC 2018 x86_64 GNU/Linux
[root@ha01 ~]# file /usr/lib/security/pam_unix.so
/usr/lib/security/pam_unix.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=2f14ba41fded472b0fae94d55e20351b98ddaa06, stripped
```

**Comment by vishalnayak** [comment]
The configuration provided in the documentation is applicable for Ubuntu 14.04 only and the pam_unix.so in that distribution has a `not_set_pass` option.
