### ISSUE TITLE
Provide public binaries and packages

### ISSUE THREAD

**Issue by siddharthist** [hashicorp/vault-ssh-helper#4]
Other Hashicorp tools, like Vault and Vagrant provide pre-built archived releases for ease of installation. This eases automated installs as well. This should be built into this project's CI/CD build.

**Comment by sethvargo** [comment]
Duplicate of https://github.com/hashicorp/vault-ssh-helper/issues/2. They are on releases.hashicorp.com.

**Comment by siddharthist** [comment]
@sethvargo Perhaps a link should be added to the README under installation?

**Comment by vishalnayak** [comment]
@siddharthist: That's a good suggestion.
Done!
