### ISSUE TITLE
validateIP function does restrict to a single IP

### ISSUE THREAD

**Issue by csschwe** [hashicorp/vault-ssh-helper#47]
In Vault if you request a new SSH OTP for a host with an IP of `10.50.100.101` and attempt to login to `10.50.100.102` the current vault-ssh-helper code it will match the IP Address of any host in the subnet.

net.Interfaces() retrieves IPs as such
```
[127.0.0.1/8 10.50.100.102/24 ::1/128]
```
When using the `belongsToCIDR` function to validate the IP addresses on the host any IP address in `10.50.100.0/24` would match.

**Comment by catsby** [comment]
Thank you for reporting this! This issue was fixed with https://github.com/hashicorp/vault-ssh-helper/pull/48 and released with https://github.com/hashicorp/vault-ssh-helper/releases/tag/v0.2.0, with a new release binary pushed here:

- https://releases.hashicorp.com/vault-ssh-helper/0.2.0/
