### ISSUE TITLE
vault-ssh-helper will no longer compile

### ISSUE THREAD

**Issue by sh3llf1sh** [hashicorp/vault-ssh-helper#49]
When running "go build" on the latest ( the error also persists with old versions of the codebase too ) I get the following error upon compilation: 

go: golang.org/x/text@v0.3.1-0.20181227161524-e6919f6577db: invalid pseudo-version: git fetch --unshallow -f https://go.googlesource.com/text in /root/go/pkg/mod/cache/vcs/38515699458adac9c8b61a0b44f9ad7a5f6edd7bcc2d7fae95930ec78f71e1b4: exit status 128:
	fatal: git fetch-pack: expected shallow lis

**Comment by kalafut** [comment]
I'm unable to reproduce this. I'd suggest wiping your go module cache if this is still an issue.
