### ISSUE TITLE
Authentication log says "Successful" but SSH fails

### ISSUE THREAD

**Issue by siddharthist** [hashicorp/vault-ssh-helper#6]
I have a setup that is almost identical to what is described in the README, but I can't log in to my host with a generated OTP. 
```
[vagrant@control-01 vagrant]$ vault-ssh-helper --version
vault-ssh-helper v0.1.0
```
Here's my configuration:
```
[vagrant@control-01 vagrant]$ cat /etc/vault/ssh-helper.hcl 
vault_addr = "https://control-01.node.consul:8200"
ssh_mount_point = "ssh"
tls_skip_verify = true
```
And my pam configuration (different from the example only in that I use `auth sufficient` instead of `auth required` but I've also tried both)
```
bash-4.2# cat /etc/pam.d/sshd 
#%PAM-1.0
auth       required     pam_sepermit.so
auth       substack     password-auth
auth       include      postlogin
# Used with polkit to reauthorize users in remote sessions
-auth      optional     pam_reauthorize.so prepare
account    required     pam_nologin.so
account    include      password-auth
password   include      password-auth
# pam_selinux.so close should be the first session rule
session    required     pam_selinux.so close
session    required     pam_loginuid.so
# pam_selinux.so open should only be followed by sessions to be executed in the user context
session    required     pam_selinux.so open env_params
session    required     pam_namespace.so
session    optional     pam_keyinit.so force revoke
session    include      password-auth
session    include      postlogin
# Used with polkit to reauthorize users in remote sessions
-session   optional     pam_reauthorize.so prepare
auth sufficient pam_exec.so quiet expose_authtok log=/tmp/vaultssh.log /usr/local/bin/vault-ssh-helper -config-file=/etc/vault/ssh-helper.hcl
auth optional pam_unix.so no_set_pass use_first_pass nodelay
```
The relevant log file:
```
bash-4.2# cat /tmp/vaultssh.log 
*** Sun Feb 14 23:26:19 2016
2016/02/14 23:26:19 [INFO] Using SSH Mount point: ssh
2016/02/14 23:26:19 [INFO] vagrant@192.168.100.101 Authenticated!
```
And my login attempt:
```
vagrant@192.168.100.101's password: 
Permission denied, please try again.
```
Am I doing something wrong? Why would `sshd` and `vault-ssh-helper` disagree on whether or not I'm authenticated?

**Comment by siddharthist** [comment]
I just realized that 
```
#@include common-auth
```
was missing from my `/etc/pam.d/sshd` configuration, but this didn't seem to make a difference either.

**Comment by siddharthist** [comment]
It looks like the example PAM configuration might have some problems:
```
Feb 15 02:13:07 control-01 unix_chkpwd[27816]: password check failed for user (vagrant)
Feb 15 02:13:07 control-01 sshd[27774]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=192.168.100.1  user=vagrant
Feb 15 02:13:07 control-01 sshd[27774]: pam_unix(sshd:auth): unrecognized option [no_set_pass]
Feb 15 02:13:07 control-01 unix_chkpwd[27826]: password check failed for user (vagrant)
Feb 15 02:13:09 control-01 sshd[27774]: Failed password for vagrant from 192.168.100.1 port 42184 ssh2
Feb 15 02:13:17 control-01 sshd[27774]: Connection closed by 192.168.100.1 [preauth]
Feb 15 02:13:17 control-01 sshd[27774]: PAM 1 more authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=192.168.100.1  user=vagrant
```

**Comment by vishalnayak** [comment]
@siddharthist 

_#@include common-auth_ is a commented out line in default ubuntu pam configuration file.
It is of no use to you.

I can see other auth instructions in the file. You can place the last two instructions at the beginning of the file and comment out the following lines:
`
auth       required     pam_sepermit.so
auth       substack     password-auth
auth       include      postlogin
# Used with polkit to reauthorize users in remote sessions
-auth      optional     pam_reauthorize.so prepare
`

The example configuration provided with vault-ssh-helper is for Ubuntu 14.04 machine.
The configuration differs with each distribution.

I also recommend disabling SELinux by doing _setenforce 0_.

The only case you see "successful" in the logs and not get authenticated is when PAM settings are not configured to succeed when ssh-helper exits gracefully.

**Comment by siddharthist** [comment]
@vishalnayak Maybe there could be more documentation on conflicting/different PAM configurations, since the instructions might not work on all distributions? In any case, I'll do some more reading on PAM and get back to you if I find a solution/get stuck. 

Also, my use case requires allowing SELinux enforcing mode. Why do you recommend disabling it? I feel like it makes sense to use Vault in tandem with SELinux :-)

**Comment by vishalnayak** [comment]
@siddharthist Sure. I will add documentation that the configuration differs with distributions.

If you can get the configurations to work with SELinux, that's great.

However, there was another thread where somebody had problems with getting ssh-helper to work.
See this: https://groups.google.com/forum/#!searchin/vault-tool/selinux/vault-tool/VKyEGaEC2rg/uvB-1LNxDQAJ
