### ISSUE TITLE
Binary does not seem to be found by system

### ISSUE THREAD

**Issue by Fibrasek** [hashicorp/vault-ssh-helper#61]
Hi,

I am trying to get the helper in an alpine machine. I downloaded, gave the permissions, made it executable but as I try to run it, I keep getting a weird error.

For example:
```
/usr/local/bin # ls -la
total 14952
...
-rwxr-xr-x    1 root     root       9483866 Dec 16 12:11 vault-ssh-helper
```

Then when I run the command:
```
/usr/local/bin # vault-ssh-helper -dev -verify-only -config=/etc/vault-ssh-helper.d/config.hcl
/bin/sh: vault-ssh-helper: not found
```
It keep saying not found, but the executable is right there. The config files do exist too.

Is there any specific packages I should add to alpine to make it run correctly? Am I missing something here?

Thanks in advance :)

**Comment by elitswarfvinge** [comment]
Hey Fibrasek,
I'm not from Hashicorp, but I have a thought about what might be the cause of your error. Does the helper start if you try to start it with a period and a slash infront of it when you are in the /usr/local/bin/ folder?
`./vault-ssh-helper -dev -verify-only -config=/etc/vault-ssh-helper.d/config.hcl` 

If it does, it might be that in your alpine setup you don't have the /usr/local/bin/ as part of your path.

**Comment by Fibrasek** [comment]
Hi @elitswarfvinge, it won't run even with `./`

**Comment by Fibrasek** [comment]
Finally we discovered that somewhat the 64-bit bin wasn't working, so we changed to the 32-bit one.
