### ISSUE TITLE
The configuration in Readme for SSH/PAM is not available in Centos7

### ISSUE THREAD

**Issue by boHam-wang** [hashicorp/vault-ssh-helper#73]
[Note]: This configuration is applicable for Ubuntu 14.04. SSH/PAM configurations differ with each platform and distribution.

When I installed vault-ssh-helper on a centos server, it didn't work. The reason is the ssh or pam configurations is not universal in different systems. Can anyone offer a configuration that can be used in Centos?
note: I have deployed a ubuntu system, and it runs well!

**Comment by boHam-wang** [comment]
close the selinux can be worked

**Comment by auqf** [comment]
disable the selinux and you must comment the line  begin with the auth and the module is password-auth
